### ISSUE TITLE
ruby 3.1 compatibility: error: '__declspec' attributes are not enabled

### ISSUE THREAD

**Issue by wlipa** [johanns/sha3#13]
The gem worked well with ruby 3.0, but after updating to ruby 3.1, the native ext fails to build with a number of errors of this form:

    compiling digest.c
    In file included from digest.c:3:
    In file included from ./sha3.h:6:
    In file included from /opt/local/include/ruby-3.1.1/ruby.h:38:
    In file included from /opt/local/include/ruby-3.1.1/ruby/ruby.h:25:
    In file included from /opt/local/include/ruby-3.1.1/ruby/defines.h:73:
    In file included from /opt/local/include/ruby-3.1.1/ruby/backward/2/attributes.h:42:
    In file included from /opt/local/include/ruby-3.1.1/ruby/internal/attr/pure.h:25:
    /opt/local/include/ruby-3.1.1/ruby/assert.h:132:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable
    support for __declspec attributes
    RBIMPL_ATTR_NORETURN()
    ^
    /opt/local/include/ruby-3.1.1/ruby/internal/attr/noreturn.h:29:33: note: expanded from macro 'RBIMPL_ATTR_NORETURN'
    # define RBIMPL_ATTR_NORETURN() __declspec(noreturn)
                                  ^

    $ ruby --version
    ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]

**Comment by johanns** [comment]
Thanks for reporting this — I’ll take a look as soon as possible.

**Comment by wlipa** [comment]
Maybe like https://github.com/weechat/weechat/issues/1605 ?

**Comment by johanns** [comment]
@wlipa Released a new version (1.0.4) that should resolve the issue. Please confirm.

Ref: #14

**Comment by wlipa** [comment]
Yes, that installs for me now.  Thank you!
